version: '3'
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db-data:/docker-entrypoint-initdb.d
    ports:
      - 6500:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 7500:8080

  vue-ui:
    build:
      context: ./app
      dockerfile: Dockerfile-Vue
    ports:
      - "8500:80"
    container_name: vue-ui
    volumes:
      - ./app:/usr/src/app/app
      - /usr/src/app/app/node_modules
