version: '3'
services:

  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - ./db-data:/docker-entrypoint-initdb.d
    ports:
      - 6500:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 7500:8080

  vue-ui:
    build:
      context: ./app
    ports:
      - "8500:80"
    volumes:
      - ./app:/usr/src/app/app
      - /usr/src/app/app/node_modules
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "--ipv4",
          "http://localhost:80/"
        ]
      interval: 1s
      timeout: 5s
      retries: 5

  container_test:
    image: node:lts-alpine
    working_dir: /usr/src/test
    volumes:
      - ./test:/usr/src/test
    environment:
      - TEST_SERVER="http://vue-ui:8500"
    depends_on:
      vue-ui:
        condition: service_healthy
    command: npm run test
